version: '3.3'
services:
    rastreogo-mariadb:
        image: 'mariadb:10.5'
        restart: unless-stopped
        container_name: rastreogo_db
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password_rastreogo
            - MYSQL_DATABASE=rastreogo_db
       ## command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db_data:/var/lib/mysql
           ## - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
            - ./create-db.sql:/tmp/create-db.sql
           
        networks:
            - quasar-network

    rastreogo-api:
        depends_on:
            - rastreogo-mariadb
        build:
            dockerfile: Dockerfile.local
            context: .
        container_name: rastreogo-api
        restart: unless-stopped
        ports:
            - '5006:5006'
        volumes:
            - ./src:/usr/src/app/src
            - ./db:/usr/src/app/db
            - ./package.json:/usr/src/app/package.json
            - /usr/src/app/node_modules
   
        env_file:
            - .env.local
        networks:
            - quasar-network

networks:
    quasar-network:
        driver: bridge

volumes:
    db_data: {}
